import { motion, AnimatePresence } from 'framer-motion'
import './FactCheckPanel.css'

function formatDate(iso) {
  if (!iso) return '—'
  try {
    const d = new Date(iso)
    return Number.isNaN(d.getTime()) ? '—' : d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })
  } catch {
    return '—'
  }
}

function AIFactCheckCard({ fc }) {
  return (
    <motion.div
      className="fact-check-panel__ai-card"
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
    >
      <div className="fact-check-panel__ai-header">
        <span className="fact-check-panel__ai-badge">AI Analysis</span>
        <span className="fact-check-panel__ai-model">Claude (Anthropic)</span>
      </div>
      {fc.rating && (
        <div className={`fact-check-panel__ai-verdict fact-check-panel__ai-verdict--${fc.rating.toLowerCase().replace(/\s+/g, '-')}`}>
          {fc.rating}
        </div>
      )}
      {fc.claim_text && (
        <p className="fact-check-panel__ai-analysis">{fc.claim_text}</p>
      )}
      <p className="fact-check-panel__ai-disclaimer">
        This analysis was generated by an AI model, not a professional fact-checker.
      </p>
    </motion.div>
  )
}

export default function FactCheckPanel({ data, loading, error }) {
  const googleChecks = data?.fact_checks?.filter(fc => !fc.is_ai_generated) || []
  const aiChecks = data?.fact_checks?.filter(fc => fc.is_ai_generated) || []

  return (
    <section className="fact-check-panel">
      <div className="fact-check-panel__header-block">
        <h2 className="fact-check-panel__title">Fact checks</h2>
      </div>

      {loading && (
        <motion.p className="fact-check-panel__state" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
          Loading fact checks…
        </motion.p>
      )}

      {error && !loading && (
        <motion.p className="fact-check-panel__state fact-check-panel__state--error" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
          {error}
        </motion.p>
      )}

      {data && !loading && !error && (
        <>
          {/* Google fact checks */}
          {googleChecks.length > 0 && (
            <>
              <p className="fact-check-panel__intro">
                From <strong>Google&apos;s Fact Check index</strong> — professional reviews by
                PolitiFact, Snopes, Reuters, and other organizations.
              </p>
              <AnimatePresence>
                <motion.ul
                  className="fact-check-panel__list"
                  initial="hidden"
                  animate="visible"
                  variants={{ visible: { transition: { staggerChildren: 0.08 } }, hidden: {} }}
                >
                  {googleChecks.map((fc) => (
                    <motion.li
                      key={fc.id}
                      className="fact-check-panel__item"
                      variants={{ hidden: { opacity: 0, y: 12 }, visible: { opacity: 1, y: 0, transition: { duration: 0.28 } } }}
                    >
                      <div className="fact-check-panel__item-header">
                        <span className="fact-check-panel__publisher">{fc.publisher || 'Unknown publisher'}</span>
                        <span className="fact-check-panel__date">{formatDate(fc.review_date)}</span>
                      </div>
                      {fc.rating && <div className="fact-check-panel__rating">{fc.rating}</div>}
                      {fc.review_url && (
                        <motion.a
                          href={fc.review_url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="fact-check-panel__link"
                          whileHover={{ x: 3 }}
                          transition={{ type: 'spring', stiffness: 400, damping: 30 }}
                        >
                          Read review →
                        </motion.a>
                      )}
                    </motion.li>
                  ))}
                </motion.ul>
              </AnimatePresence>
            </>
          )}

          {/* AI fact checks (shown when no Google results) */}
          {aiChecks.length > 0 && (
            <div className="fact-check-panel__ai-section">
              {googleChecks.length === 0 && (
                <p className="fact-check-panel__intro">
                  No indexed reviews found for this story yet —{' '}
                  <strong>AI analysis</strong> generated instead.
                </p>
              )}
              {aiChecks.map(fc => <AIFactCheckCard key={fc.id} fc={fc} />)}
            </div>
          )}

          {/* Nothing from either source */}
          {!data.has_results && aiChecks.length === 0 && googleChecks.length === 0 && (
            <motion.div
              className="fact-check-panel__google-empty"
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
            >
              <p className="fact-check-panel__message">
                No fact-check results found for this story yet.
              </p>
            </motion.div>
          )}
        </>
      )}
    </section>
  )
}
