import { render, screen } from '@testing-library/react'
import { describe, it, expect } from 'vitest'
import FactCheckPanel from '../FactCheckPanel.jsx'

const GOOGLE_FC = {
  id: 1,
  claim_text: 'Infrastructure spending claim',
  claim_reviewed: 'Senate passed infrastructure bill',
  rating: 'Mostly True',
  publisher: 'PolitiFact',
  review_url: 'https://example.com/factcheck/1',
  review_date: '2026-03-15T12:00:00',
  is_ai_generated: false,
}

const AI_FC = {
  id: 2,
  claim_text: 'The core facts are correct. Key claims: Bill passed; Bipartisan support.',
  claim_reviewed: 'Senate passes major infrastructure bill',
  rating: 'Mostly Accurate',
  publisher: 'Claude AI (Anthropic)',
  review_url: null,
  review_date: null,
  is_ai_generated: true,
}

describe('FactCheckPanel', () => {
  it('shows loading state', () => {
    render(<FactCheckPanel loading={true} data={null} error={null} />)
    expect(screen.getByText(/loading fact checks/i)).toBeInTheDocument()
  })

  it('shows error state', () => {
    render(<FactCheckPanel loading={false} data={null} error="Network error" />)
    expect(screen.getByText(/network error/i)).toBeInTheDocument()
  })

  it('renders Google fact check with publisher, rating, and link', () => {
    render(<FactCheckPanel loading={false} error={null} data={{ has_results: true, fact_checks: [GOOGLE_FC] }} />)
    expect(screen.getByText('PolitiFact')).toBeInTheDocument()
    expect(screen.getByText('Mostly True')).toBeInTheDocument()
    expect(screen.getByRole('link', { name: /read review/i })).toHaveAttribute('href', GOOGLE_FC.review_url)
  })

  it('renders AI fact check with badge and verdict', () => {
    render(<FactCheckPanel loading={false} error={null} data={{ has_results: true, fact_checks: [AI_FC] }} />)
    expect(screen.getByText('AI Analysis')).toBeInTheDocument()
    expect(screen.getByText('Mostly Accurate')).toBeInTheDocument()
    expect(screen.getByText(/generated by an AI model/i)).toBeInTheDocument()
  })

  it('shows no-match message when has_results is false and no checks', () => {
    render(<FactCheckPanel loading={false} error={null} data={{ has_results: false, fact_checks: [] }} />)
    expect(screen.getByText(/no fact-check results found/i)).toBeInTheDocument()
  })

  it('shows AI intro text when only AI checks are present', () => {
    render(<FactCheckPanel loading={false} error={null} data={{ has_results: true, fact_checks: [AI_FC] }} />)
    expect(screen.getByText(/no indexed reviews found/i)).toBeInTheDocument()
  })
})
